spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show_sql: true
  application:
    name: warehouse

  sql:
    init:
      mode: always

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:8432/warehouse-db
    username: warehouse
    password: warehouse

server:
  port: 0