spring:
  application:
    name: warehouse
  config:
    import: "configserver:"
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        serviceId: config-server
      retry:
        useRandomPolicy: true
        max-interval: 6000
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  circuitbreaker:
    enabled: true
  httpclient:
    enabled: true

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
    preferIpAddress: true
    hostname: localhost
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    ru.yandex.practicum.warehouse.client: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    feign: DEBUG
    org.springframework.cloud.client.loadbalancer: DEBUG

